
spring:
  profiles:
    active: default
  application:
    name: holunda
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: validate
    show-sql: true

# Camunda
camunda:
  bpm:
    database:
      schema-update: false
    id-generator: prefixed
    admin-user:
      id: admin
    filter:
      create: All
